name: Go

on:
  push:
    branches: [ "main", "cube", "hypercube", "tesseract" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout=5m --enable=unparam --enable=misspell --enable=prealloc

    - name: Protogen test
      run: make proto-gen

    - name: Test
      run: make test
