name: End-to-end test

on:
  push:
    branches: [ "main", "cube", "release/**" ]
  pull_request:
    types: [ opened, reopened ]
    paths: [ "**.go", "**.mod", "**.sum" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup network
      run: |
        mkdir ~/genesis
        cd tests/e2e && docker compose up -d
        docker ps
        sleep 20

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
          go-version-file: 'go.mod'

    - name: Test
      run: |
        make test

    - name: End-to-end test
      run: cd tests/e2e && go test

    - name: Teardown
      run: cd tests/e2e && docker compose down
